# Generated by Django 5.0 on 2026-01-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reported',
            field=models.BooleanField(db_default=models.Value(False)),
        ),
    ]
