# Generated by Django 5.0 on 2026-01-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_review_reported'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reported',
            new_name='is_reported',
        ),
    ]
